language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - "easy_install -U setuptools"
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: echo
